### ISSUE TITLE
openssl dependency is not set

### ISSUE THREAD

**Issue by Dantee296** [libimobiledevice-win32/libimobiledevice-vs#10]
hi i followed steps but openssl dependency is not set 
can u explain how to do that ? and which version to use ?

**Comment by qmfrederik** [comment]
At compile time, the OpenSSL dependency is installed via VCPKG. See the README and the CI script for more information about that.

**Comment by qmfrederik** [comment]
I'm going to go ahead and close this issue. The build works fine in CI. If you have further questions, please feel free to reopen with detailed info.
