### ISSUE TITLE
idevicerestore fails to build on Windows - Cannot open include file: 'ziperr.h'

### ISSUE THREAD

**Issue by rcmpayne** [libimobiledevice-win32/libimobiledevice-vs#2]
cant seem to find zip.h/ziperr.h in any package from vcpkg

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'ziperr.h': No such file or directory	idevicerestore

**Comment by qmfrederik** [comment]
See the README. You need zlib and libzip. Make sure to set %BUILD_ARCH% to x86 or x64 based on your bitness. The azure-pipelines.yml file has all the answers :smile:. Feel free to send a PR if the README is unclear ;-)

```
vcpkg\vcpkg install libiconv:%BUILD_ARCH%-windows zlib:%BUILD_ARCH%-windows openssl:%BUILD_ARCH%-windows dirent:%BUILD_ARCH%-windows getopt:%BUILD_ARCH%-windows curl:%BUILD_ARCH%-windows libzip:%BUILD_ARCH%-windows
```

**Comment by rcmpayne** [comment]
This is what i was using
.\vcpkg install cpr:x64-windows libiconv:x64-windows zlib:x64-windows openssl:x64-windows dirent:x64-windows getopt:x64-windows curl:x64-windows libzip:x64-windows

.\vcpkg install cpr:x86-windows libiconv:x86-windows zlib:x86-windows openssl:x86-windows dirent:x86-windows getopt:x86-windows curl:x86-windows libzip:x86-windows

**Comment by rcmpayne** [comment]
As you can see, zipper is not listed in those packages

![image](https://user-images.githubusercontent.com/5473836/52341773-e35aac80-29e9-11e9-9084-0478d80ad816.png)

![image](https://user-images.githubusercontent.com/5473836/52341805-f9686d00-29e9-11e9-8a60-3493cff77696.png)

**Comment by qmfrederik** [comment]
I couldn't find any reference to `ziperr.h` in the source code. Can you please let me know where that file is referenced? Other than that, CI passes + works for me, so I'll close this issue for now. Feel free to reopen.
