### ISSUE TITLE
After the project is compiled, it seems that there are some tools missing, idevicebackup2.exe can not be found!!!

### ISSUE THREAD

**Issue by hehenibuxing** [libimobiledevice-win32/libimobiledevice-vs#3]
![TIM图片20190315151048](https://user-images.githubusercontent.com/36142720/54414564-8c589d80-4734-11e9-8cf3-581a993ae852.png)

**Comment by qmfrederik** [comment]
That's correct; this repository doesn't build any of the tools (yet).

You can either build the tools directly from the libimobiledevice-win32/libimobiledevice repository, download them from the build artifacts in the Azure Pipelines builds, or submit a PR to this repository that add support for building them there 😄 .

**Comment by qmfrederik** [comment]
idevicebackup2 was added a while ago, hope it helps.
